services:
  trajimpu:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trajimpu
    working_dir: /app

    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

    shm_size: 96gb
    stdin_open: true
    tty: true

    volumes:
      - /mnt/dataimputationgroup/Outputs:/app/Outputs
      - /mnt/dataimputationgroup/Data:/app/Data
      - .:/app

    networks:
      - trajviz

    command: ["python", "-u", "-m", "src.predict_simple"]
  
  tensorboard:
    image: tensorflow/tensorflow:latest
    container_name: tensorboard
    ports:
      - "6006:6006"
    volumes:
      - /mnt/dataimputationgroup/Outputs:/app/Outputs
    command: ["tensorboard" , "--logdir=/app/Outputs/Tensorboard", "--host=0.0.0.0"]

networks:
  trajviz:
    external: true
    name: trajviz_TrajNet
