  name: base
  channels:
    - conda-forge
  dependencies:
    - pandas
    - psycopg2
    - pyproj
    - proj
    - proj-data
    - matplotlib
    - shapely
    - tensorboard
    - tensorflow
    - scipy 
    - gdal
